// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faxatpiqtuyxsmodmuua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZheGF0cGlxdHV5eHNtb2RtdXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTI4NTQsImV4cCI6MjA2NTAyODg1NH0.fKiYpe9dp1xEsv4EFvh0QhirboA5KSOjDrQaDG94qyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);